//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tongbro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hint
    {
        public int HintID { get; set; }
        public string Keyword { get; set; }
        public string Category { get; set; }
    }
}
